// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGDwkTU2EtKku4q9W1OJk0VuC3y9h3rg',
    appId: '1:332532868582:web:2c95ba3c2a6c427e5ca227',
    messagingSenderId: '332532868582',
    projectId: 'blend-bristo',
    authDomain: 'blend-bristo.firebaseapp.com',
    storageBucket: 'blend-bristo.appspot.com',
    measurementId: 'G-VXXKECK01J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0R_gI0HnmFFojb4IVdwujd_X8_l53dJ8',
    appId: '1:332532868582:android:eeececed27d2dd9b5ca227',
    messagingSenderId: '332532868582',
    projectId: 'blend-bristo',
    storageBucket: 'blend-bristo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pj0m880oGpC8rHwmSZOW5LCeEP6xsfw',
    appId: '1:332532868582:ios:ad6a41bc8f575e745ca227',
    messagingSenderId: '332532868582',
    projectId: 'blend-bristo',
    storageBucket: 'blend-bristo.appspot.com',
    iosBundleId: 'com.example.blendBristo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4pj0m880oGpC8rHwmSZOW5LCeEP6xsfw',
    appId: '1:332532868582:ios:8923fe3d07258e005ca227',
    messagingSenderId: '332532868582',
    projectId: 'blend-bristo',
    storageBucket: 'blend-bristo.appspot.com',
    iosBundleId: 'com.example.blendBristo.RunnerTests',
  );
}
